title: Erica (Eunjae) McLean
#logo:
description: Experienced and versatile professional with a decade-long track record across finance, technology, trade, and law, adept in data science and business analytics, dedicated to driving informed decisions and operational excellence as a business analyst.
show_downloads: true
theme: jekyll-theme-minimal
